// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "../test-sdk";
import { CalculateServerStatsTimer } from "./calculate_server_stats_timer_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `calculate_server_stats_timer`.
 *
 * Obtain a handle from the [`calculateServerStatsTimer`] property on [`RemoteTables`],
 * like `ctx.db.calculateServerStatsTimer`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.calculateServerStatsTimer.on_insert(...)`.
 */
export class CalculateServerStatsTimerTableHandle {
  tableCache: TableCache<CalculateServerStatsTimer>;

  constructor(tableCache: TableCache<CalculateServerStatsTimer>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<CalculateServerStatsTimer> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `scheduled_id` unique index on the table `calculate_server_stats_timer`,
   * which allows point queries on the field of the same name
   * via the [`CalculateServerStatsTimerScheduledIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.calculateServerStatsTimer.scheduled_id().find(...)`.
   *
   * Get a handle on the `scheduled_id` unique index on the table `calculate_server_stats_timer`.
   */
  scheduled_id = {
    // Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): CalculateServerStatsTimer | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.scheduled_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: CalculateServerStatsTimer) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: CalculateServerStatsTimer) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: CalculateServerStatsTimer) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: CalculateServerStatsTimer) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: CalculateServerStatsTimer, newRow: CalculateServerStatsTimer) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: CalculateServerStatsTimer, newRow: CalculateServerStatsTimer) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
