// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "../test-sdk";
import { Pixel } from "./pixel_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `pixels`.
 *
 * Obtain a handle from the [`pixels`] property on [`RemoteTables`],
 * like `ctx.db.pixels`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.pixels.on_insert(...)`.
 */
export class PixelsTableHandle {
  tableCache: TableCache<Pixel>;

  constructor(tableCache: TableCache<Pixel>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Pixel> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `pixel_id` unique index on the table `pixels`,
   * which allows point queries on the field of the same name
   * via the [`PixelsPixelIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.pixels.pixel_id().find(...)`.
   *
   * Get a handle on the `pixel_id` unique index on the table `pixels`.
   */
  pixel_id = {
    // Find the subscribed row whose `pixel_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Pixel | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.pixel_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Pixel) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Pixel) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Pixel) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Pixel) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Pixel, newRow: Pixel) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Pixel, newRow: Pixel) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
