// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "../test-sdk";
import { ServerStats } from "./server_stats_type";
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `server_stats`.
 *
 * Obtain a handle from the [`serverStats`] property on [`RemoteTables`],
 * like `ctx.db.serverStats`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.serverStats.on_insert(...)`.
 */
export class ServerStatsTableHandle {
  tableCache: TableCache<ServerStats>;

  constructor(tableCache: TableCache<ServerStats>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<ServerStats> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `stats_id` unique index on the table `server_stats`,
   * which allows point queries on the field of the same name
   * via the [`ServerStatsStatsIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.serverStats.stats_id().find(...)`.
   *
   * Get a handle on the `stats_id` unique index on the table `server_stats`.
   */
  stats_id = {
    // Find the subscribed row whose `stats_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ServerStats | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.stats_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: ServerStats) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ServerStats) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: ServerStats) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ServerStats) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ServerStats, newRow: ServerStats) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ServerStats, newRow: ServerStats) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
